[package]
name = "zenoh-bmr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
foxglove = "0.9.0"
log = "0.4.27"
mcap = "0.23.0"
serde_json = "1.0.140"
tokio = "1.46.0"
zenoh = { version = "1.4.0", features = ["internal"] }
